# Generated by Django 6.0.7 on 2026-07-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🍛', max_length=10)),
                ('bgColor', models.CharField(default='#5b45b0', max_length=10)),
            ],
        ),
    ]
